import type { ModelIntelligence } from "@/lib/types";
import { sleep } from "./client";

export const modelApi = {
  async getModelIntelligence(): Promise<ModelIntelligence> {
    await sleep(220);

    return {
      currentModel: {
        name: "Trustline Gradient Boosted Scorecard (XGBoost)",
        version: "v1.4.0-prod",
        trainedAt: "2026-02-15T08:30:00Z",
        datasetVersion: "KE-SYNTH-BENCH-2026.02",
        status: "active",
        observations: 148_500,
      },
      comparison: [
        {
          name: "XGBoost Alternative-Data Scorecard",
          tag: "primary",
          auc: 0.884,
          ks: 54.2,
          precision: 0.812,
          recall: 0.776,
          f1: 0.793,
          calibration: 0.042,
          interpretability: "high",
        },
        {
          name: "Logistic Regression Baseline (Scorecard)",
          tag: "baseline",
          auc: 0.768,
          ks: 38.6,
          precision: 0.704,
          recall: 0.652,
          f1: 0.677,
          calibration: 0.089,
          interpretability: "high",
        },
      ],
      roc: [
        { fpr: 0.0, tpr: 0.0, baseline: 0.0 },
        { fpr: 0.05, tpr: 0.42, baseline: 0.22 },
        { fpr: 0.1, tpr: 0.68, baseline: 0.38 },
        { fpr: 0.15, tpr: 0.79, baseline: 0.51 },
        { fpr: 0.2, tpr: 0.86, baseline: 0.62 },
        { fpr: 0.3, tpr: 0.92, baseline: 0.74 },
        { fpr: 0.4, tpr: 0.95, baseline: 0.81 },
        { fpr: 0.6, tpr: 0.98, baseline: 0.91 },
        { fpr: 0.8, tpr: 0.99, baseline: 0.96 },
        { fpr: 1.0, tpr: 1.0, baseline: 1.0 },
      ],
      precisionRecall: [
        { recall: 0.1, precision: 0.96 },
        { recall: 0.2, precision: 0.94 },
        { recall: 0.3, precision: 0.92 },
        { recall: 0.4, precision: 0.89 },
        { recall: 0.5, precision: 0.86 },
        { recall: 0.6, precision: 0.83 },
        { recall: 0.7, precision: 0.79 },
        { recall: 0.8, precision: 0.72 },
        { recall: 0.9, precision: 0.61 },
        { recall: 1.0, precision: 0.45 },
      ],
      calibration: [
        { predicted: 2.0, observed: 1.8 },
        { predicted: 5.0, observed: 4.9 },
        { predicted: 10.0, observed: 9.6 },
        { predicted: 15.0, observed: 14.8 },
        { predicted: 20.0, observed: 21.2 },
        { predicted: 30.0, observed: 29.5 },
        { predicted: 45.0, observed: 46.1 },
        { predicted: 60.0, observed: 58.8 },
      ],
      confusionMatrix: {
        truePositive: 1240,
        falsePositive: 280,
        trueNegative: 7850,
        falseNegative: 350,
      },
      bandPerformance: [
        { band: "Low Risk", population: 5400, observedDefaultRate: 0.012, predictedPd: 0.014 },
        { band: "Medium Risk", population: 2700, observedDefaultRate: 0.046, predictedPd: 0.048 },
        { band: "High Risk", population: 1100, observedDefaultRate: 0.148, predictedPd: 0.152 },
        { band: "Severe Risk", population: 520, observedDefaultRate: 0.342, predictedPd: 0.338 },
      ],
      featureImportance: [
        {
          feature: "repaymentConsistency",
          label: "Repayment Consistency Index",
          importance: 0.28,
          description: "Tracks on-time completion of previous mobile loan cycles and utility obligations.",
        },
        {
          feature: "daysPastDue",
          label: "Historical Days Past Due (DPD)",
          importance: 0.22,
          description: "Maximum delinquency duration across all historical facilities.",
        },
        {
          feature: "utilisationRatio",
          label: "Cash Flow Utilisation Ratio",
          importance: 0.16,
          description: "Proportion of monthly cash inflow immediately committed to outgoing obligations.",
        },
        {
          feature: "previousDefaults",
          label: "Prior 90+ DPD Write-offs",
          importance: 0.12,
          description: "Count of historic unrecovered credit write-offs across financial institutions.",
        },
        {
          feature: "transactionVolatility",
          label: "Mobile-Money Inflow Volatility",
          importance: 0.09,
          description: "Standard deviation of weekly mobile-money deposits relative to mean volume.",
        },
        {
          feature: "accountTenureMonths",
          label: "Mobile Account Tenure",
          importance: 0.06,
          description: "Duration of active mobile wallet and banking history in months.",
        },
        {
          feature: "loanToIncome",
          label: "Requested Loan-to-Income",
          importance: 0.04,
          description: "Requested facility principal compared to estimated 6-month verifiable revenue.",
        },
        {
          feature: "transactionFrequency",
          label: "Monthly Transaction Velocity",
          importance: 0.03,
          description: "Average number of inbound commercial transactions processed per month.",
        },
      ],
      monitoring: {
        predictionVolume: [
          { date: "Oct 25", volume: 1840 },
          { date: "Nov 25", volume: 2190 },
          { date: "Dec 25", volume: 2680 },
          { date: "Jan 26", volume: 2420 },
          { date: "Feb 26", volume: 2890 },
          { date: "Mar 26", volume: 3150 },
        ],
        averagePd: [
          { date: "Oct 25", avgPd: 6.8 },
          { date: "Nov 25", avgPd: 6.5 },
          { date: "Dec 25", avgPd: 7.1 },
          { date: "Jan 26", avgPd: 6.2 },
          { date: "Feb 26", avgPd: 5.9 },
          { date: "Mar 26", avgPd: 5.7 },
        ],
        scoreDistribution: [
          { bucket: "300–450", count: 420 },
          { bucket: "450–550", count: 880 },
          { bucket: "550–650", count: 1840 },
          { bucket: "650–750", count: 4250 },
          { bucket: "750–850", count: 5400 },
          { bucket: "850–900", count: 2100 },
        ],
        driftIndicator: [
          { feature: "Repayment Consistency", psi: 0.032, status: "stable" },
          { feature: "Transaction Volatility", psi: 0.084, status: "watch" },
          { feature: "Utilisation Ratio", psi: 0.041, status: "stable" },
          { feature: "Days Past Due", psi: 0.021, status: "stable" },
          { feature: "Account Tenure", psi: 0.018, status: "stable" },
        ],
        featureAvailability: [
          { feature: "Mobile-Money Statements", availability: 0.992 },
          { feature: "Historical Delinquency", availability: 0.985 },
          { feature: "Utility Bill Receipts", availability: 0.842 },
          { feature: "Merchant Turnover API", availability: 0.915 },
        ],
        lastEvaluation: "2026-03-01T04:00:00Z",
      },
    };
  },
};
